# Redirigir todas las solicitudes HTTP a HTTPS
server {
    listen 80;
    server_name padeleros.vip www.padeleros.vip;

    return 301 https://$host$request_uri;
}

# Manejar tráfico HTTPS en el puerto 443 y redirigir a localhost:4000
server {
    listen 443 ssl;
    server_name padeleros.vip www.padeleros.vip;

    ssl_certificate /etc/letsencrypt/live/padeleros.vip/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/padeleros.vip/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://localhost:4000; # Puerto donde corre tu aplicación Next.js
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}

# Manejar tráfico HTTPS en el puerto 3000 y redirigir a localhost:3000
server {
    listen 8443 ssl;
    server_name padeleros.vip www.padeleros.vip;

    ssl_certificate /etc/letsencrypt/live/padeleros.vip/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/padeleros.vip/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://localhost:3000; # Puerto donde corre tu API NestJS
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
